export const featured = [
  {
    type: "Photography",
    Image: "/course.png",
    by: "by Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    price: "$29.0",
    duration: "2 Weeks",
    numOfStudent: 166,
  },
  {
    type: "Photography",
    Image: "/course.png",
    by: "by Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    price: "$29.0",
    duration: "2 Weeks",
    numOfStudent: 166,
  },
  {
    type: "Photography",
    Image: "/course.png",
    by: "by Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    price: "$29.0",
    duration: "2 Weeks",
    numOfStudent: 166,
  },
  {
    type: "Photography",
    Image: "/course.png",
    by: "by Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    price: "$29.0",
    duration: "2 Weeks",
    numOfStudent: 166,
  },
  {
    type: "Photography",
    Image: "/course.png",
    by: "by Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    price: "$29.0",
    duration: "2 Weeks",
    numOfStudent: 166,
  },
  {
    type: "Photography",
    Image: "/course.png",
    by: "by Determined-Poitras",
    name: "Create an LMS Website with LearnPress",
    price: "$29.0",
    duration: "2 Weeks",
    numOfStudent: 166,
  },
];
